### ISSUE TITLE
Final Capstone: Kanban Board PR

### ISSUE THREAD

**Issue by federicaulzurrun** [oovillagran/final-capstone-back-end#1]
### We are 5 in total: @oovillagran, @Mylo16 , @kkolade , @rashedarman  and I @federicaulzurrun 

**Here is the link to our [GitHub Project](https://github.com/users/oovillagran/projects/9)**

**For this part of the project we:**

- Set up the Kanban Board.
- Added Fron-End and Back-End labels to be more organized.
- Divided us into Front-end and Back-end
- Assigned the task as equal as possible having the time points as reference 

Here are the **screenshots**
![image](https://github.com/oovillagran/final-capstone-back-end/assets/122847613/f428598f-b769-4a1a-94c5-7a52e5ff7ee3)
![image](https://github.com/oovillagran/final-capstone-back-end/assets/122847613/2f415fa5-df22-4a79-a0f2-c7a098b6cc7e)
![image](https://github.com/oovillagran/final-capstone-back-end/assets/122847613/704c471f-aef6-41d5-aa94-6cdfda2a90b6)
![image](https://github.com/oovillagran/final-capstone-back-end/assets/122847613/f14a6f08-3373-4b27-874d-3f9b444ba002)
![image](https://github.com/oovillagran/final-capstone-back-end/assets/122847613/033eef12-6f34-49b1-aff0-d0baebb8eb5e)

**Comment by Meltrust** [comment]
Hi @federicaulzurrun,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @federicaulzurrun,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, have been assigned and pointed according to the reqs✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
